services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    
    # Run server
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
    env_file:
      - ./src/.env
    environment:
      - POSTGRES_SERVER=db
      - REDIS_CACHE_HOST=redis
    ports:
       - "8000:8000"
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env

  db:
    image: postgres:15-alpine
    env_file:
      - ./src/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  #-------- uncomment to run tests --------
  # pytest:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile 
  #   env_file:
  #     - ./src/.env
  #   depends_on:
  #     - db
  #   command: python -m pytest ./tests
  #   volumes:
  #     - .:/code

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./deployment/loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./src/app/logs:/var/log/app
      - ./deployment/promtail/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./deployment/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki

volumes:
  postgres-data:
  redis-data:
